/*let number = Math.floor(Math.random()*10)+1; //+1 pour exclure 0 et inclure 10
let answer = 0;

while(answer !== number){
   answer = parseInt(window.prompt("Devinez un nombre entre 1 et 10"),10);
   if(answer<number){
    window.alert("Nombre trop petit !");
   }
   else if(answer>number){
      window.alert("Nombre trop grand !");
   }
   else(
      window.alert("Bravo !")
   )
}*/

//array() = [] = tableau de données

